buildVariable: false
familyName: Noto Sans Modi
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans Devanagari
  ranges:
  - end: 2365
    start: 2365
recipeProvider: noto
sources:
- NotoSansModi.glyphs
